# Site settings
title: Rondy
email: rondysousa@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rondy.github.io/" # the base hostname & protocol for your site
twitter_username: rondy
github_username:  rondy

# Build settings
markdown: kramdown
